import { join } from "node:path";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { ArduinoCliAdapter } from "@carduino/arduino-cli";
import { buildHardwareContext, diagnoseSerial, DriverRegistry, ExperimentEngine, FlashAndObserveService, generateVerificationReport, ProjectService, SimpleSimulationAdapter, SqliteProjectStore } from "@carduino/core";
import type { ComponentInstance, Connection } from "@carduino/core";
import { parse } from "yaml";
import { readFileSync } from "node:fs";

const text = (value: unknown) => ({ content: [{ type: "text" as const, text: JSON.stringify(value, null, 2) }] });
function runtime(root: string) { const store = new SqliteProjectStore(join(root, ".har", "project.sqlite")); return { store, projects: new ProjectService(store), experiments: new ExperimentEngine(store), arduino: new ArduinoCliAdapter() }; }
export function createHarMcpServer(root = process.env.HAR_PROJECT_DIR ?? process.cwd()): McpServer {
  const server = new McpServer({ name: "carduino", version: "0.1.0" }, { instructions: "HAR controls local embedded tooling and records evidence. It is not an AI agent. Never claim a physical result without evidence or a human confirmation." });
  server.registerTool("inspect_environment", { description: "Inspect Arduino CLI and connected board candidates.", inputSchema: {} }, async () => { const r = runtime(root); try { return text({ arduinoCli: await r.arduino.inspect(), boards: await r.arduino.discover() }); } finally { r.store.close(); } });
  server.registerTool("create_project", { description: "Create a persisted HAR project.", inputSchema: { id: z.string().optional() } }, async ({ id }) => { const r = runtime(root); try { return text(r.projects.create(id === undefined ? {} : { id })); } finally { r.store.close(); } });
  server.registerTool("get_project_state", { description: "Load project state.", inputSchema: { projectId: z.string() } }, async ({ projectId }) => { const r = runtime(root); try { return text(r.projects.load(projectId)); } finally { r.store.close(); } });
  server.registerTool("update_hardware_model", { description: "Persist declared components and connections, then make the project ready to build.", inputSchema: { projectId: z.string(), expectedRevision: z.number().int().positive(), componentsJson: z.string().default("[]"), connectionsJson: z.string().default("[]") } }, async ({ projectId, expectedRevision, componentsJson, connectionsJson }) => { const r = runtime(root); try { let revision = expectedRevision; const current = r.projects.load(projectId); if (current.lifecycle === "created") { r.projects.patch(projectId, revision++, { lifecycle: "hardware_planning" }); } const result = r.projects.patch(projectId, revision++, { components: JSON.parse(componentsJson) as ComponentInstance[], connections: JSON.parse(connectionsJson) as Connection[] }); const ready = result.project.lifecycle === "hardware_planning" ? r.projects.patch(projectId, result.project.revision, { lifecycle: "ready_to_build" }).project : result.project; return text(ready); } finally { r.store.close(); } });
  server.registerTool("get_hardware_context", { description: "Return compact project, board, and persisted operation context without raw logs.", inputSchema: { projectId: z.string(), detail: z.enum(["compact", "detailed"]).optional() } }, async ({ projectId, detail }) => { const r = runtime(root); try { const project = r.projects.load(projectId); const boards = await r.arduino.discover(); const latest = r.store.loadRecord<unknown>("flash_runs", projectId); return text(buildHardwareContext(project, { ...(boards[0] === undefined ? {} : { board: boards[0] }), ...(latest === undefined ? {} : { recentSerial: { evidenceId: "flash_run", lineCount: 0, capturedAt: project.updatedAt } }) }, detail ?? "compact")); } finally { r.store.close(); } });
  server.registerTool("list_drivers", { description: "List installed declarative hardware drivers.", inputSchema: { directory: z.string().optional() } }, async ({ directory }) => { const registry = new DriverRegistry(); registry.loadDirectory(directory ?? join(root, "examples", "drivers")); return text(registry.list()); });
  server.registerTool("compile_firmware", { description: "Compile an Arduino sketch through the Arduino CLI adapter and store its structured result.", inputSchema: { projectId: z.string(), sketchPath: z.string(), fqbn: z.string() } }, async ({ projectId, sketchPath, fqbn }) => { const r = runtime(root); try { const compile = await r.arduino.compile({ sketchPath, fqbn }); const artifact = { id: `artifact_${crypto.randomUUID()}`, projectId, digest: `sha256:${Buffer.from(`${sketchPath}:${fqbn}:${compile.stdout}`).toString("base64url")}`, compile }; r.store.saveRecord("artifacts", artifact); return text({ id: artifact.id, projectId, digest: artifact.digest, compile: { success: compile.success, fqbn: compile.fqbn, estimatedFlashBytes: compile.estimatedFlashBytes, estimatedRamBytes: compile.estimatedRamBytes, stderr: compile.stderr.slice(-4000) } }); } finally { r.store.close(); } });
  server.registerTool("flash_and_observe", { description: "Compile, flash, wait for serial, capture startup output, diagnose it, and persist one structured result.", inputSchema: { projectId: z.string(), expectedRevision: z.number().int().positive(), sketchPath: z.string(), fqbn: z.string(), port: z.string(), baudRate: z.number().int().positive().optional(), captureDurationMs: z.number().int().positive().max(60000).optional() } }, async ({ projectId, expectedRevision, sketchPath, fqbn, port, baudRate, captureDurationMs }) => { const r = runtime(root); try { const service = new FlashAndObserveService(r.projects, { toolchain: r.arduino, flash: r.arduino, serial: r.arduino, usb: r.arduino, boards: r.arduino }); const result = await service.execute({ projectId, expectedRevision, sketchPath, fqbn, port, ...(baudRate === undefined ? {} : { baudRate }), ...(captureDurationMs === undefined ? {} : { captureDurationMs }) }); r.store.saveRecord("flash_runs", { id: projectId, result }); return text({ operationId: result.operationId, status: result.status, stage: result.stage, compile: { success: result.compile.success, fqbn: result.compile.fqbn, estimatedFlashBytes: result.compile.estimatedFlashBytes, estimatedRamBytes: result.compile.estimatedRamBytes }, ...(result.flash === undefined ? {} : { flash: { success: result.flash.success, fqbn: result.flash.fqbn, port: result.flash.port } }), ...(result.serial === undefined ? {} : { serial: { evidenceId: result.serial.evidenceId, preview: result.serial.text.slice(0, 4000) } }), diagnostics: result.diagnostics, retryable: result.retryable, suggestedNextActions: result.suggestedNextActions }); } finally { r.store.close(); } });
  server.registerTool("get_diagnostics", { description: "Capture a bounded serial window and return evidence-linked diagnostic findings.", inputSchema: { port: z.string(), baudRate: z.number().int().positive().default(115200), durationMs: z.number().int().positive().max(60000).default(3000) } }, async ({ port, baudRate, durationMs }) => { const r = runtime(root); try { const capture = await r.arduino.capture(port, baudRate, durationMs); const evidenceId = `serial_${crypto.randomUUID()}`; return text({ capture: { evidenceId, ...capture }, diagnostics: diagnoseSerial([{ id: evidenceId, timestampMs: Date.now(), text: capture.text, rawBase64: capture.rawBase64 }]) }); } finally { r.store.close(); } });
  server.registerTool("simulate_experiment", { description: "Run deterministic behavioral simulation; results are explicitly simulated.", inputSchema: { ledOn: z.boolean().optional(), numericName: z.string().optional(), numericValue: z.number().optional() } }, async ({ ledOn, numericName, numericValue }) => text(new SimpleSimulationAdapter().simulate({ digitalInputs: ledOn === undefined ? {} : { LED_BUILTIN: ledOn }, numericStreams: numericName === undefined || numericValue === undefined ? {} : { [numericName]: [numericValue] } })));
  server.registerTool("run_experiment", { description: "Run a deterministic experiment and return a persisted human-action request when it pauses.", inputSchema: { definitionPath: z.string(), serialText: z.string().optional() } }, async ({ definitionPath, serialText }) => { const r = runtime(root); try { const definition = parse(readFileSync(definitionPath, "utf8")); return text(r.experiments.start(definition, serialText ?? "")); } finally { r.store.close(); } });
  server.registerTool("resume_experiment", { description: "Resume a persisted experiment after a schema-valid human response.", inputSchema: { definitionPath: z.string(), runId: z.string(), token: z.string(), confirmed: z.boolean() } }, async ({ definitionPath, runId, token, confirmed }) => { const r = runtime(root); try { return text(r.experiments.resume(parse(readFileSync(definitionPath, "utf8")), runId, token, { confirmed })); } finally { r.store.close(); } });
  server.registerTool("generate_runtime_report", { description: "Generate evidence-based JSON verification output for a persisted experiment run.", inputSchema: { projectId: z.string(), runId: z.string() } }, async ({ projectId, runId }) => { const r = runtime(root); try { const project = r.projects.load(projectId); const run = r.store.loadRecord<Parameters<typeof generateVerificationReport>[0]["run"]>("experiment_runs", runId); if (run === undefined) throw new Error("Experiment run not found"); return text(generateVerificationReport({ projectId, hardwareModelRevision: project.revision, run })); } finally { r.store.close(); } });
  return server;
}
if (import.meta.url === `file://${process.argv[1]}`) { const server = createHarMcpServer(); await server.connect(new StdioServerTransport()); }
